// Mock Data for Stalford EduCore LMS

export const users = {
  student: {
    id: 'student-1',
    name: 'Itadori Yuji',
    email: 'student@stalford.edu',
    role: 'student' as const,
    avatar: 'IY',
    class: 'P5-Math-C',
  },
  tutor: {
    id: 'tutor-1',
    name: 'Gojo Satoru',
    email: 'tutor@stalford.edu',
    role: 'tutor' as const,
    avatar: 'GS',
    subject: 'Mathematics',
  },
};

export const subjects = [
  {
    id: 'mathematics',
    name: 'Mathematics',
    class: 'P5-Math-C',
    icon: '📐',
    color: 'blue',
    totalTopics: 5,
    progress: 15,
    confidence: 35,
    worksheetsCompleted: 1,
    worksheetsTotal: 3,
    topicsCompleted: 0,
    topicsTotal: 5,
  },
  {
    id: 'science',
    name: 'Science',
    class: 'P5-Science-B',
    icon: '🔬',
    color: 'green',
    totalTopics: 5,
    progress: 100,
    confidence: 93,
    worksheetsCompleted: 5,
    worksheetsTotal: 5,
    topicsCompleted: 5,
    topicsTotal: 5,
  },
  {
    id: 'english',
    name: 'English',
    class: 'P5-English-A',
    icon: '📚',
    color: 'purple',
    totalTopics: 5,
    progress: 0,
    confidence: 0,
    worksheetsCompleted: 0,
    worksheetsTotal: 1,
    topicsCompleted: 0,
    topicsTotal: 5,
  },
];

export const topics = {
  mathematics: [
    {
      id: 'algebra',
      name: 'Algebra',
      description: 'Learn the fundamentals of algebraic expressions and equations',
      confidence: 41,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 2,
      worksheets: [
        { id: 'ws-alg-1', name: 'Algebraic Expressions', completed: true, questions: 5, points: 100, timeLimit: 30 },
        { id: 'ws-alg-2', name: 'Algebra Practice Set', completed: false, questions: 8, points: 80, timeLimit: 40 },
      ],
      materials: [
        { id: 'mat-alg-1', name: 'Algebra Basics Study Guide', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-15', size: '2.3 MB', description: 'Comprehensive study guide covering all algebra basics' },
        { id: 'mat-alg-2', name: 'Algebra Practice Problems', type: 'past-paper', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-20', size: '1.8 MB', description: 'Extra practice problems for mastery' },
      ],
    },
    {
      id: 'geometry',
      name: 'Geometry',
      description: 'Explore shapes, angles, and spatial reasoning',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 2,
      worksheets: [
        { id: 'ws-geo-1', name: 'Geometry Basics', completed: false, questions: 6, points: 90, timeLimit: 35 },
        { id: 'ws-geo-2', name: 'Advanced Geometry', completed: false, questions: 7, points: 95, timeLimit: 45 },
      ],
      materials: [
        { id: 'mat-geo-1', name: 'Geometry Formula Cheat Sheet', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-10', size: '0.5 MB', description: 'Quick reference for all geometry formulas' },
        { id: 'mat-geo-2', name: 'Geometry Complete Notes', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-12', size: '3.1 MB', description: 'Complete lecture notes for geometry module' },
        { id: 'mat-geo-3', name: 'PSLE Geometry Past Year Paper 2025', type: 'past-paper', uploadedBy: 'Mr. Kumar Raj', date: '2026-02-01', size: '4.2 MB', description: 'Official PSLE past year paper for geometry' },
      ],
    },
    {
      id: 'fractions',
      name: 'Fractions',
      description: 'Understanding and manipulating fractions',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 2,
      worksheets: [
        { id: 'ws-frac-1', name: 'Introduction to Fractions', completed: false, questions: 10, points: 100, timeLimit: 30 },
        { id: 'ws-frac-2', name: 'Mixed Numbers Practice', completed: false, questions: 8, points: 80, timeLimit: 40 },
      ],
      materials: [],
    },
    {
      id: 'decimals',
      name: 'Decimals',
      description: 'Working with decimal numbers and operations',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-dec-1', name: 'Decimals Worksheet 1', completed: false, questions: 10, points: 100, timeLimit: 30 },
      ],
      materials: [],
    },
    {
      id: 'word-problems',
      name: 'Word Problems',
      description: 'Applying math concepts to real-world scenarios',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-wp-1', name: 'Word Problems Practice', completed: false, questions: 8, points: 80, timeLimit: 40 },
      ],
      materials: [],
    },
  ],
  science: [
    {
      id: 'cell-biology',
      name: 'Cell Biology',
      description: 'Structure and functions of cells',
      confidence: 47,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-cb-1', name: 'Cell Biology Quiz', completed: true, questions: 10, points: 100, timeLimit: 30 },
      ],
      materials: [
        { id: 'mat-cb-1', name: 'PSLE Science Cell Biology Past Year 2075', type: 'past-paper', uploadedBy: 'Ms. Chen Li', date: '2026-02-15', size: '3.5 MB', description: 'Past year paper for cell biology' },
      ],
    },
    {
      id: 'forces-motion',
      name: 'Forces and Motion',
      description: 'Understanding forces, motion and their relationships',
      confidence: 46,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-fm-1', name: 'Forces and Motion Worksheet', completed: true, questions: 8, points: 80, timeLimit: 40 },
      ],
      materials: [
        { id: 'mat-fm-1', name: 'Forces and Motion Notes', type: 'notes', uploadedBy: 'Ms. Chen Li', date: '2026-01-20', size: '2.8 MB', description: 'Comprehensive notes on forces and motion' },
        { id: 'mat-fm-2', name: 'PSLE Forces Past Year Paper 2075', type: 'past-paper', uploadedBy: 'Ms. Chen Li', date: '2026-02-10', size: '4.1 MB', description: 'Past year exam paper on forces' },
      ],
    },
    {
      id: 'plants',
      name: 'Plants',
      description: 'Plant structure, photosynthesis and growth',
      confidence: 46,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-pl-1', name: 'Plants and Photosynthesis', completed: true, questions: 8, points: 80, timeLimit: 35 },
      ],
      materials: [],
    },
    {
      id: 'human-systems',
      name: 'Human Systems',
      description: 'Digestive, respiratory, and circulatory systems',
      confidence: 47,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-hs-1', name: 'Human Body Systems', completed: true, questions: 10, points: 100, timeLimit: 30 },
      ],
      materials: [],
    },
    {
      id: 'ecosystems',
      name: 'Ecosystems',
      description: 'Food chains, habitats and environmental science',
      confidence: 46,
      maxConfidence: 50,
      lessonAttended: true,
      worksheetsCompleted: 1,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-eco-1', name: 'Ecosystems and Food Chains', completed: true, questions: 8, points: 80, timeLimit: 35 },
      ],
      materials: [],
    },
  ],
  english: [
    {
      id: 'grammar-essentials',
      name: 'Grammar Essentials',
      description: 'Core grammar rules and sentence construction',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-ge-1', name: 'Grammar Essentials Quiz', completed: false, questions: 4, points: 40, timeLimit: 20 },
      ],
      materials: [
        { id: 'mat-ge-1', name: 'Vocabulary Builder Week 1', type: 'notes', uploadedBy: 'Ms. Priya S', date: '2026-01-08', size: '1.2 MB', description: 'Weekly vocabulary building exercises' },
      ],
    },
    {
      id: 'comprehension',
      name: 'Comprehension',
      description: 'Reading comprehension and analytical skills',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-comp-1', name: 'Comprehension Practice', completed: false, questions: 10, points: 100, timeLimit: 45 },
      ],
      materials: [],
    },
    {
      id: 'creative-writing',
      name: 'Creative Writing',
      description: 'Developing writing skills and creative expression',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-cw-1', name: 'Creative Writing Exercise', completed: false, questions: 3, points: 30, timeLimit: 60 },
      ],
      materials: [],
    },
    {
      id: 'vocabulary',
      name: 'Vocabulary',
      description: 'Building a strong vocabulary foundation',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 1,
      worksheets: [
        { id: 'ws-voc-1', name: 'Vocabulary Test Week 1', completed: false, questions: 20, points: 100, timeLimit: 25 },
      ],
      materials: [],
    },
    {
      id: 'oral-communication',
      name: 'Oral Communication',
      description: 'Speaking skills and oral examination preparation',
      confidence: 0,
      maxConfidence: 50,
      lessonAttended: false,
      worksheetsCompleted: 0,
      worksheetsTotal: 0,
      worksheets: [],
      materials: [],
    },
  ],
};

export const submissions = [
  {
    id: 'sub-1',
    worksheetId: 'ws-alg-1',
    worksheetName: 'Algebraic Expressions',
    subjectName: 'Mathematics',
    topicName: 'Algebra',
    status: 'completed',
    grade: 'A',
    totalPoints: 100,
    scoredPoints: 100,
    questions: 5,
    totalTime: 10,
    avgTimePerQuestion: 2,
    submittedDate: '2026-02-15',
    reviewedBy: 'Mr. Kumar Raj',
    gradedDate: '2026-02-17',
  },
  {
    id: 'sub-2',
    worksheetId: 'ws-ge-1',
    worksheetName: 'Grammar Essentials Quiz',
    subjectName: 'English',
    topicName: 'Grammar Essentials',
    status: 'processing',
    grade: null,
    totalPoints: 100,
    scoredPoints: null,
    questions: 4,
    totalTime: null,
    avgTimePerQuestion: null,
    submittedDate: '2026-03-10',
    reviewedBy: null,
    gradedDate: null,
  },
];

export const continuelearning = [
  {
    topicName: 'Algebra',
    subjectName: 'Mathematics',
    subjectId: 'mathematics',
    topicId: 'algebra',
    status: 'worksheet',
    message: '1 worksheet remaining',
  },
  {
    topicName: 'Geometry',
    subjectName: 'Mathematics',
    subjectId: 'mathematics',
    topicId: 'geometry',
    status: 'lesson-pending',
    message: '1 worksheet remaining',
  },
  {
    topicName: 'Grammar Essentials',
    subjectName: 'English',
    subjectId: 'english',
    topicId: 'grammar-essentials',
    status: 'lesson-pending',
    message: '1 worksheet remaining',
  },
];

export const analyticsData = {
  mathematics: {
    subjectId: 'mathematics',
    subjectName: 'Mathematics',
    class: 'P5 Math C',
    overallConfidence: 35,
    strongestTopic: { name: 'Geometry', score: 49 },
    needsFocus: { name: 'Word Problems', score: 25 },
    weeklyTrend: [
      { week: 'Week 1', confidence: 20 },
      { week: 'Week 2', confidence: 25 },
      { week: 'Week 3', confidence: 30 },
      { week: 'Week 4', confidence: 35 },
    ],
    topicBreakdown: [
      { topic: 'Algebra', score: 41, max: 50 },
      { topic: 'Geometry', score: 0, max: 50 },
      { topic: 'Fractions', score: 0, max: 50 },
      { topic: 'Decimals', score: 0, max: 50 },
      { topic: 'Word Problems', score: 0, max: 50 },
    ],
    commonMistakes: [
      'Confusing order of operations in algebraic expressions',
      'Difficulty with negative numbers in equations',
      'Incorrectly simplifying fractions',
    ],
    aiRecommendations: [
      'Review order of operations (BODMAS) with practice problems',
      'Practice geometry worksheets to build confidence',
      'Focus on word problem strategies',
    ],
  },
  science: {
    subjectId: 'science',
    subjectName: 'Science',
    class: 'P5-Science-B',
    overallConfidence: 93,
    strongestTopic: { name: 'Cell Biology', score: 95 },
    needsFocus: { name: 'Forces and Motion', score: 91 },
    weeklyTrend: [
      { week: 'Week 1', confidence: 75 },
      { week: 'Week 2', confidence: 80 },
      { week: 'Week 3', confidence: 88 },
      { week: 'Week 4', confidence: 93 },
    ],
    topicBreakdown: [
      { topic: 'Cell Biology', score: 47, max: 50 },
      { topic: 'Forces', score: 46, max: 50 },
      { topic: 'Plants', score: 46, max: 50 },
      { topic: 'Human Systems', score: 47, max: 50 },
      { topic: 'Ecosystems', score: 46, max: 50 },
    ],
    commonMistakes: [
      'Minor errors in labeling cell organelles',
      'Confusing balanced and unbalanced forces',
    ],
    aiRecommendations: [
      'Continue current study pace to maintain performance',
      'Review forces and motion concepts for final mastery',
      'Excellent work on cell biology!',
    ],
  },
  english: {
    subjectId: 'english',
    subjectName: 'English',
    class: 'P5 Progress',
    overallConfidence: 0,
    strongestTopic: { name: 'Grammar Essentials', score: 0 },
    needsFocus: { name: 'Grammar Essentials', score: 0 },
    weeklyTrend: [
      { week: 'Week 1', confidence: 0 },
      { week: 'Week 2', confidence: 0 },
      { week: 'Week 3', confidence: 0 },
      { week: 'Week 4', confidence: 0 },
    ],
    topicBreakdown: [
      { topic: 'Grammar', score: 0, max: 50 },
      { topic: 'Comprehension', score: 0, max: 50 },
      { topic: 'Writing', score: 0, max: 50 },
      { topic: 'Vocabulary', score: 0, max: 50 },
      { topic: 'Oral', score: 0, max: 50 },
    ],
    commonMistakes: [
      'No submissions yet to analyze',
    ],
    aiRecommendations: [
      'Begin with Grammar Essentials worksheet to start tracking progress',
      'Complete lesson attendance to unlock full analytics',
    ],
  },
};

export const classes = [
  {
    id: 'p5-math-a',
    name: 'P5-Math-A',
    subject: 'Mathematics',
    level: 'Primary 5',
    studentCount: 10,
    classAverage: 84,
    needAttention: 1,
    tutor: 'Gojo Satoru',
  },
  {
    id: 'p5-math-b',
    name: 'P5-Math-B',
    subject: 'Mathematics',
    level: 'Primary 5',
    studentCount: 10,
    classAverage: 91,
    needAttention: 0,
    tutor: 'Gojo Satoru',
  },
];

export const classStudents = {
  'p5-math-a': [
    { id: 'st-1', name: 'Ryan Lee', initials: 'RL', overallConfidence: 62, algebra: 55, geometry: 70, fractions: 65, decimals: 58, wordProblems: 50, worksheetsCompleted: 8, avgTime: 4.2, commonIssues: 'Word Problems, Fractions' },
    { id: 'st-2', name: 'Sophie Wong', initials: 'SW', overallConfidence: 88, algebra: 90, geometry: 85, fractions: 92, decimals: 88, wordProblems: 85, worksheetsCompleted: 12, avgTime: 3.1, commonIssues: 'None' },
    { id: 'st-3', name: 'Emma Tan', initials: 'ET', overallConfidence: 91, algebra: 95, geometry: 88, fractions: 94, decimals: 91, wordProblems: 87, worksheetsCompleted: 14, avgTime: 2.8, commonIssues: 'None' },
    { id: 'st-4', name: 'Daniel Ng', initials: 'DN', overallConfidence: 77, algebra: 75, geometry: 80, fractions: 72, decimals: 78, wordProblems: 80, worksheetsCompleted: 10, avgTime: 3.5, commonIssues: 'Algebra' },
    { id: 'st-5', name: 'Chloe Lim', initials: 'CL', overallConfidence: 85, algebra: 87, geometry: 82, fractions: 88, decimals: 85, wordProblems: 83, worksheetsCompleted: 11, avgTime: 3.2, commonIssues: 'None' },
    { id: 'st-6', name: 'Jonathan Lim', initials: 'JL', overallConfidence: 93, algebra: 95, geometry: 91, fractions: 96, decimals: 93, wordProblems: 90, worksheetsCompleted: 15, avgTime: 2.5, commonIssues: 'None' },
    { id: 'st-7', name: 'Damian Koh', initials: 'DK', overallConfidence: 79, algebra: 82, geometry: 76, fractions: 80, decimals: 78, wordProblems: 79, worksheetsCompleted: 9, avgTime: 3.8, commonIssues: 'Geometry' },
    { id: 'st-8', name: 'Priya Raj', initials: 'PR', overallConfidence: 87, algebra: 89, geometry: 85, fractions: 90, decimals: 87, wordProblems: 84, worksheetsCompleted: 13, avgTime: 3.0, commonIssues: 'None' },
    { id: 'st-9', name: 'Lucas Chen', initials: 'LC', overallConfidence: 82, algebra: 84, geometry: 80, fractions: 85, decimals: 82, wordProblems: 79, worksheetsCompleted: 11, avgTime: 3.4, commonIssues: 'None' },
    { id: 'st-10', name: 'Aisha Patel', initials: 'AP', overallConfidence: 95, algebra: 97, geometry: 93, fractions: 98, decimals: 95, wordProblems: 92, worksheetsCompleted: 16, avgTime: 2.3, commonIssues: 'None' },
  ],
  'p5-math-b': [
    { id: 'st-11', name: 'Marcus Tan', initials: 'MT', overallConfidence: 89, algebra: 91, geometry: 87, fractions: 92, decimals: 89, wordProblems: 86, worksheetsCompleted: 13, avgTime: 2.9, commonIssues: 'None' },
    { id: 'st-12', name: 'Lily Zhao', initials: 'LZ', overallConfidence: 94, algebra: 96, geometry: 92, fractions: 97, decimals: 94, wordProblems: 91, worksheetsCompleted: 15, avgTime: 2.4, commonIssues: 'None' },
    { id: 'st-13', name: 'Kevin Ho', initials: 'KH', overallConfidence: 86, algebra: 88, geometry: 84, fractions: 89, decimals: 86, wordProblems: 83, worksheetsCompleted: 12, avgTime: 3.1, commonIssues: 'None' },
    { id: 'st-14', name: 'Natalie Sim', initials: 'NS', overallConfidence: 91, algebra: 93, geometry: 89, fractions: 94, decimals: 91, wordProblems: 88, worksheetsCompleted: 14, avgTime: 2.7, commonIssues: 'None' },
    { id: 'st-15', name: 'Aaron Lew', initials: 'AL', overallConfidence: 88, algebra: 90, geometry: 86, fractions: 91, decimals: 88, wordProblems: 85, worksheetsCompleted: 13, avgTime: 3.0, commonIssues: 'None' },
    { id: 'st-16', name: 'Grace Teo', initials: 'GT', overallConfidence: 96, algebra: 98, geometry: 94, fractions: 99, decimals: 96, wordProblems: 93, worksheetsCompleted: 17, avgTime: 2.2, commonIssues: 'None' },
    { id: 'st-17', name: 'Bryan Ong', initials: 'BO', overallConfidence: 83, algebra: 85, geometry: 81, fractions: 86, decimals: 83, wordProblems: 80, worksheetsCompleted: 11, avgTime: 3.3, commonIssues: 'None' },
    { id: 'st-18', name: 'Hannah Yeo', initials: 'HY', overallConfidence: 90, algebra: 92, geometry: 88, fractions: 93, decimals: 90, wordProblems: 87, worksheetsCompleted: 14, avgTime: 2.8, commonIssues: 'None' },
    { id: 'st-19', name: 'Felix Goh', initials: 'FG', overallConfidence: 92, algebra: 94, geometry: 90, fractions: 95, decimals: 92, wordProblems: 89, worksheetsCompleted: 15, avgTime: 2.6, commonIssues: 'None' },
    { id: 'st-20', name: 'Isabelle Ng', initials: 'IN', overallConfidence: 95, algebra: 97, geometry: 93, fractions: 98, decimals: 95, wordProblems: 92, worksheetsCompleted: 16, avgTime: 2.3, commonIssues: 'None' },
  ],
};

export const classAnalytics = {
  'p5-math-a': {
    topicPerformance: [
      { topic: 'Fractions', average: 82 },
      { topic: 'Decimals', average: 84 },
      { topic: 'Algebra', average: 85 },
      { topic: 'Geometry', average: 83 },
      { topic: 'Word Problems', average: 82 },
    ],
  },
  'p5-math-b': {
    topicPerformance: [
      { topic: 'Fractions', average: 93 },
      { topic: 'Decimals', average: 91 },
      { topic: 'Algebra', average: 93 },
      { topic: 'Geometry', average: 90 },
      { topic: 'Word Problems', average: 88 },
    ],
  },
};

export const autoGraderSubmissions = [
  {
    id: 'ag-1',
    studentName: 'Sophie Wong',
    studentInitials: 'SW',
    worksheetName: 'Decimals Worksheet 1',
    class: 'P5-Math-A',
    status: 'pending-review',
    aiScore: 96,
    submittedDate: '2026-03-20',
  },
  {
    id: 'ag-2',
    studentName: 'Chloe Lim',
    studentInitials: 'CL',
    worksheetName: 'Algebra Basics Worksheet',
    class: 'P5-Math-A',
    status: 'pending-review',
    aiScore: 87,
    submittedDate: '2026-03-19',
  },
  {
    id: 'ag-3',
    studentName: 'Ryan Lee',
    studentInitials: 'RL',
    worksheetName: 'Decimals Worksheet 1',
    class: 'P5-Math-A',
    status: 'processing',
    aiScore: null,
    submittedDate: '2026-03-21',
  },
  {
    id: 'ag-4',
    studentName: 'Jonathan Lim',
    studentInitials: 'JL',
    worksheetName: 'Algebra Basics',
    class: 'P5-Math-A',
    status: 'approved',
    aiScore: 96,
    submittedDate: '2026-03-18',
  },
  {
    id: 'ag-5',
    studentName: 'Damian Koh',
    studentInitials: 'DK',
    worksheetName: 'Algebra Basics',
    class: 'P5-Math-A',
    status: 'not-submitted',
    aiScore: null,
    submittedDate: null,
  },
];

export const reviewSubmission = {
  id: 'ag-1',
  studentName: 'Sophie Wong',
  worksheetName: 'Decimals Worksheet 1',
  status: 'pending-review',
  aiScore: 8,
  aiScoreMax: 10,
  aiConfidence: 77,
  questions: [
    {
      id: 1,
      question: 'What is 3.5 + 2.7?',
      studentAnswer: '6.2',
      correctAnswer: '6.2',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Student correctly added the decimal numbers. 3.5 + 2.7 = 6.2. The student showed clear working and arrived at the correct answer.',
    },
    {
      id: 2,
      question: 'Convert 0.75 to a fraction in its simplest form.',
      studentAnswer: '3/4',
      correctAnswer: '3/4',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct conversion. 0.75 = 75/100 = 3/4 in simplest form. Student demonstrated understanding of decimal to fraction conversion.',
    },
    {
      id: 3,
      question: 'Calculate 5.6 × 0.4',
      studentAnswer: '2.24',
      correctAnswer: '2.24',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct multiplication. Student properly placed the decimal point in the answer.',
    },
    {
      id: 4,
      question: 'Which is greater: 0.8 or 0.79?',
      studentAnswer: '0.8',
      correctAnswer: '0.8',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct. 0.8 = 0.80 > 0.79. Student correctly compared decimal values.',
    },
    {
      id: 5,
      question: 'Round 4.678 to 2 decimal places.',
      studentAnswer: '4.68',
      correctAnswer: '4.68',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct rounding. Looking at the third decimal (8 ≥ 5), student correctly rounded up the second decimal.',
    },
    {
      id: 6,
      question: 'Express 7/8 as a decimal.',
      studentAnswer: '0.875',
      correctAnswer: '0.875',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct. 7 ÷ 8 = 0.875. Student accurately performed the division.',
    },
    {
      id: 7,
      question: 'If a ribbon is 2.5 m long and you cut off 0.75 m, how much is left?',
      studentAnswer: '1.65 m',
      correctAnswer: '1.75 m',
      isCorrect: false,
      marks: 0,
      maxMarks: 1,
      aiExplanation: 'Incorrect. 2.5 - 0.75 = 1.75 m, not 1.65 m. The student made an arithmetic error in subtraction. They may have incorrectly aligned the decimal points when subtracting.',
    },
    {
      id: 8,
      question: 'Order from smallest to largest: 0.5, 0.05, 0.55, 0.505',
      studentAnswer: '0.05, 0.5, 0.505, 0.55',
      correctAnswer: '0.05, 0.5, 0.505, 0.55',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct ordering. Student successfully compared multiple decimal values with different numbers of decimal places.',
    },
    {
      id: 9,
      question: 'What is 10% of 4.5?',
      studentAnswer: '4.5',
      correctAnswer: '0.45',
      isCorrect: false,
      marks: 0,
      maxMarks: 1,
      aiExplanation: 'Incorrect. 10% of 4.5 = 0.45. The student confused the percentage calculation, possibly multiplying by 1 instead of 0.1, or misunderstood the meaning of percentage.',
    },
    {
      id: 10,
      question: 'A bottle holds 1.5 litres. How many 0.25 litre cups can be filled?',
      studentAnswer: '6',
      correctAnswer: '6',
      isCorrect: true,
      marks: 1,
      maxMarks: 1,
      aiExplanation: 'Correct. 1.5 ÷ 0.25 = 6 cups. Student correctly applied division of decimals to solve the word problem.',
    },
  ],
};

export const materials = [
  { id: 'mat-1', name: 'Forces and Motion Notes', subject: 'Science', topic: 'Forces and Motion', type: 'notes', uploadedBy: 'Ms. Chen Li', date: '2026-01-20', size: '2.8 MB', description: 'Comprehensive notes covering forces, motion, and Newtons laws' },
  { id: 'mat-2', name: 'PSLE Forces Past Year Paper 2075', subject: 'Science', topic: 'Forces and Motion', type: 'past-paper', uploadedBy: 'Ms. Chen Li', date: '2026-02-10', size: '4.1 MB', description: 'Official PSLE past year paper focused on forces and motion' },
  { id: 'mat-3', name: 'Vocabulary Builder Week 1', subject: 'English', topic: 'Vocabulary', type: 'notes', uploadedBy: 'Ms. Priya S', date: '2026-01-08', size: '1.2 MB', description: 'Weekly vocabulary building exercises with definitions and example sentences' },
  { id: 'mat-4', name: 'Geometry Formula Cheat Sheet', subject: 'Mathematics', topic: 'Geometry', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-10', size: '0.5 MB', description: 'Quick reference card with all essential geometry formulas' },
  { id: 'mat-5', name: 'Geometry Complete Notes', subject: 'Mathematics', topic: 'Geometry', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-12', size: '3.1 MB', description: 'Complete lecture notes for the geometry module' },
  { id: 'mat-6', name: 'Algebra Practice Problems', subject: 'Mathematics', topic: 'Algebra', type: 'past-paper', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-20', size: '1.8 MB', description: 'Extra practice problems for mastering algebra concepts' },
  { id: 'mat-7', name: 'PSLE Geometry Past Year Paper 2025', subject: 'Mathematics', topic: 'Geometry', type: 'past-paper', uploadedBy: 'Mr. Kumar Raj', date: '2026-02-01', size: '4.2 MB', description: 'Official PSLE past year paper for geometry section' },
  { id: 'mat-8', name: 'Algebra Basics Study Guide', subject: 'Mathematics', topic: 'Algebra', type: 'notes', uploadedBy: 'Mr. Kumar Raj', date: '2026-01-15', size: '2.3 MB', description: 'Comprehensive study guide covering all algebra basics' },
  { id: 'mat-9', name: 'PSLE Science Cell Biology Past Year 2075', subject: 'Science', topic: 'Cell Biology', type: 'past-paper', uploadedBy: 'Ms. Chen Li', date: '2026-02-15', size: '3.5 MB', description: 'Past year paper focused on cell biology topics' },
];

export const tutorMaterials = [
  { id: 'tm-1', name: 'Introduction to Fractions', subject: 'Mathematics', topic: 'Fractions', type: 'video', uploadedBy: 'Gojo Satoru', date: '2026-01-05', size: '145 MB', description: 'Video lesson introducing fraction concepts' },
  { id: 'tm-2', name: 'Fractions Practice Quiz', subject: 'Mathematics', topic: 'Fractions', type: 'quiz', uploadedBy: 'Gojo Satoru', date: '2026-01-10', size: '0.3 MB', description: 'Interactive quiz for fractions practice' },
  { id: 'tm-3', name: 'Decimals Worksheet 1', subject: 'Mathematics', topic: 'Decimals', type: 'worksheet', uploadedBy: 'Gojo Satoru', date: '2026-01-15', size: '0.8 MB', description: 'Worksheet for decimal operations' },
  { id: 'tm-4', name: 'Algebra Study Notes', subject: 'Mathematics', topic: 'Algebra', type: 'notes', uploadedBy: 'Gojo Satoru', date: '2026-01-20', size: '1.5 MB', description: 'Study notes for algebra module' },
  { id: 'tm-5', name: '2025 Mid-Year Exam Paper', subject: 'Mathematics', topic: 'All Topics', type: 'past-paper', uploadedBy: 'Gojo Satoru', date: '2026-02-01', size: '3.2 MB', description: '2025 mid-year examination paper' },
];

export const attendanceRecords = [
  {
    id: 'att-1',
    class: 'P5-Math-A',
    date: '2026-03-20',
    startTime: '14:00',
    endTime: '16:00',
    mode: 'Physical',
    markedBy: 'Tutor Gojo',
    students: [
      { name: 'Emma Tan', status: 'present', note: '' },
      { name: 'Ryan Lee', status: 'present', note: '' },
      { name: 'Sophie Wong', status: 'late', note: 'Arrived 15 mins late' },
    ],
  },
  {
    id: 'att-2',
    class: 'P5-Math-B',
    date: '2026-03-20',
    startTime: '16:00',
    endTime: '18:00',
    mode: 'Online',
    markedBy: 'Tutor Gojo',
    students: [
      { name: 'Emma Tan', status: 'present', note: '' },
      { name: 'Ryan Lee', status: 'absent', note: '' },
      { name: 'Sophie Wong', status: 'present', note: '' },
    ],
  },
];

export const recentSubmissions = [
  { studentName: 'Sophie Wong', worksheet: 'Decimals Worksheet 1', class: 'P5-Math-A', status: 'pending-review' },
  { studentName: 'Ryan Lee', worksheet: 'Decimals Worksheet 1', class: 'P5-Math-A', status: 'processing' },
  { studentName: 'Daniel Ng', worksheet: 'Decimals Worksheet 1', class: 'P5-Math-A', status: 'not-submitted' },
];
